<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <AssemblyName>GE2D3D.EditorSuite</AssemblyName>
    <RootNamespace>GE2D3D.EditorSuite</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GE2D3D.MapEditor\GE2D3D.MapEditor.csproj" />
    <ProjectReference Include="..\RenderTest\RenderTest.csproj" />
    <ProjectReference Include="..\Prism.Modules.D3D\Prism.Modules.D3D.csproj" />
  </ItemGroup>

</Project>
